### ISSUE TITLE
Missed events

### ISSUE THREAD

**Issue by myfreexp** [quarck/CalendarNotification#196]
Installed the app last night, and when I tested it, it worked so far. But today I didn't get any notificiation for two real events already. Any clue what the reason might be?

Just testing some fake events, will revert.

OnePlus 3T with Marshmallow 6.01. 'setAlarmClock' was enabled, but now I disabled to see if this is working more reliable. Notifications in the stock calendar app are disabled.

**Comment by whispy** [comment]
Do you have the app whitelisted in your Doze settings? See: https://www.google.com/amp/www.valuewalk.com/2015/11/how-to-stop-apps-from-using-doze-on-android-6-0-marshmallow/amp/

(I'd recommend whitelisting all calendar-related apps).

**Comment by quarck** [comment]
Thank you for reporting this bug.

Please try leaving notifications in the stock calendar enabled. In this case if you didn't receive notification from this app - at least you would see something from the stock. 
In general, when normal even is fired (it is originating from Calendar Provider - it is a part of Android OS itself), this app would receive event before the stock calendar, and app would mark it as "dismissed" so stock calendar would not show this event. If app cannot receive / parse the event, that it would leave event untouched and then stock calendar would handle it. This would be very helpful in identifying the cause of the issue.

Doze settings - yes, that's good recommendation. I don't have pure Android device to test with, so I wasn't sure if it is possible to allow app to be non-optimized. I was testing on Galaxy S6, it has very customized interface which is quite different from stock android. 
So yes - please disable app optimization for this app. 

P.S. At the moment I'm very busy with doing part-time college and main job, so I would not be able to fix any issues until end of May. But I would try helping finding some workaround.

**Comment by myfreexp** [comment]
For now, I have just followed the advice of @whispy and did whitelist the app in the doze settings (another MM setting I wasn't aware of, BTW) - let's see how it will work.

What did happen a few times already this evening: I'm getting a notification where no event is to be notified at all. But just the sound, not a visible notification. Not sure where this did come from, but given the times when this notifications did happen, they may come from those test events I did use yesterday evening (which I did delete of course) - so it looks as if CN would still "have them in mind" in some way...?

I will now assign a different sound to CN so that I can be sure if the notification is coming from CN or not. Will revert.

**Comment by myfreexp** [comment]
> For now, I have just followed the advice of @whispy and did whitelist the app in the doze settings (another MM setting I wasn't aware of, BTW) - let's see how it will work.

Doesn't work, today no notification for an event again. :(

I'll now whitelist the calendar app itself to the Doze settings, as suggested by @whispy and check if this will help.

**Comment by quarck** [comment]
Please leave notifications enabled in your main calendar app as well, if possible. If Calendar Notifications works correctly, it should intercept event notification before stock / Google calendar sees it, so stock / Google calendar would not fire the event at all. But if Calendar Notification can't handle the event for some reason - you would at least see it from your stock / Google calendar.

P.S. would you be able to collect some adb logs from your device shortly after seeing this issue? If necessary, I can provide the instructions.

**Comment by whispy** [comment]
Are the events that do not fire notifications one-off events or repeated events?

**Comment by myfreexp** [comment]
> Please leave notifications enabled in your main calendar app as well, if possible. If Calendar Notifications works correctly, it should intercept event notification before stock / Google calendar sees it, so stock / Google calendar would not fire the event at all. But if Calendar Notification can't handle the event for some reason - you would at least see it from your stock / Google calendar.

Will try that, but first I'd like to test if whitelisting the calendar app to the Doze settings alone might help.

> P.S. would you be able to collect some adb logs from your device shortly after seeing this issue? If necessary, I can provide the instructions.

Sure, I'm technically able to use ADB (but am not too familiar with it). Please send instructions.

> Are the events that do not fire notifications one-off events or repeated events?

One-off events. Didn't check repeated events yet.

**Comment by quarck** [comment]
> Sure, I'm technically able to use ADB (but am not too familiar with it). Please send instructions.

Thanks, log file would be really a great help. Please find instructions below, sorry if you might think that some items are described in way too much details. I don't know how familiar you are with android development, so it is better to give more detailed instructions then less detailed, and you could skip whatever you know how to do yourself.

I would assume you are using Windows. In case of Linux / Mac it is all pretty much the same with exception of the app you would be using for accessing command line. 

1) First if you don't have adb on your system, please download package for your system from here: 

https://developer.android.com/studio/releases/platform-tools.html 

It needs no installation, just unpack the archive to somewhere on your hard drive. Let say c:\adb (so adb.exe would be available at c:\adb\adb.exe ). 

2) Enable "Developer Mode" on your phone before attempting to reproduce the issue. Without it many Android devices would only keep Error and Warning level logs, but not Debug level logs. 

If you haven't used this mode before, you need to go Android Settings -> About Device -> Software Info, find 'Build number' entry and tap on it quickly approximately 10-15 times. It would show toast "You are now a developer" when it's done. 

After that's done, go to Android Settings -> Developer options and enable the global switch at the top. 

3) Now wait until the issue is reproduced :) 

4) Once you have it reproduced - go once again to Android Settings -> Developer options and enable "USB Debugging". Don't forget to switch "USB Debugging" back after getting the logs from the device since it is considered unsecure to keep it enabled all the time. 

5) Connect android device to your pc / laptop with USB cable. If device prompts you about allowing access over USB - click "Allow". 

6) Start cmd.exe on your pc/laptop (Win+R, cmd.exe, <enter>) and go to the folder where you have adb tools unpacked. For example: 

cd c:\adb 

7) Finally run adb.exe to collect logs from the system: 

adb logcat -v threadtime -d  -b main -b events -b system > _output_file_path.log_ 

Replace _output_file_path.log_ with the actual file you what to use for output. 

Most likely android device would ask you about permissions only at this stage, so click "allow" on the device (if screen is already locked - unlock and check if there are any pending prompts)


After generating log file, I would recommend checking it for any personal information that could have leaked into there (Calendar Notifications would never log any personal info, but other apps can). 

And then finally - forward me the log (either attach it here or better send it to my email quarck@gmail.com, so if you miss some private / personal data, it would not be available to all GitHub users). 

Thanks once again

**Comment by whispy** [comment]
@myfreexp, any update?

**Comment by myfreexp** [comment]
Not yet, sorry. After I did whitelist the calendar app, the notifications seem to work so far. But I'll keep watching.

OTOH, I'm now getting notifications from time to time, where there is no calendar (or any other) event at all. I'm wondering if these are old (test) events which are still in the memory and have not been deleted...?

But as the sound is different to the one that I did recently assign to CalendarNotification, I'm not even sure if they're comimg from this app at all.

**Comment by whispy** [comment]
They could be notifications from the Google calendar, if you never disabled
them in that app.

**Comment by quarck** [comment]
> OTOH, I'm now getting notifications from time to time, where there is no calendar (or any other) event at all. I'm wondering if these are old (test) events which are still in the memory and have not been deleted...? 

It would be helpful if you could grab (and send me) the logs shortly after seeing this (no need for adb, just using app built-in log collection should be sufficient). Just to make sure there are no bugs. 

P.S. It could be also a reminder, check what are your reminder interval settings

**Comment by quarck** [comment]
Should get better with the implementation of failback paths for event notifications (#208)
