### ISSUE TITLE
[HIGHEST PRIORITY] TODO: Failback event paths

### ISSUE THREAD

**Issue by quarck** [quarck/CalendarNotification#208]
Some devices (notably Samsungs) have issues with firing events, and from analyzing log files it seems like there is an issue with Calendar Provider service on Samsung devices. 

A few other approaches could be implemented to ensure no event is mis-handled: 

<strike>1. Sticky Calendar approach </strike> - cannot implement it on Android 7.0 and above

2. Scan events manually for next fire and set alarm independently of Calendar Provider

**Comment by solf** [comment]
My OnePlus 3T (Marshmallow + su + suhide + xposed) has issues with calendar notifications as well (they tend to do not fire at all unless event was created less than 1-2 days before) so I'm very interested in this support (as e.g. Smooth Calendar widget works properly -- it sees all upcoming events and thus it should be possible to determine when the next notification should be fired).

**Comment by solf** [comment]
So since this is a particular problem for me (couldn't get working notifications on my OnePlus 3T), I've decided to take a stab at it myself. Now the code (I'll provide extract below) is very low quality because I know neither Android programming nor Kotlin -- and thus my goal was to make the simplest thing that could possibly work (including such thing as using a file to persist HashMap as I didn't want to figure out how to do it properly).

With that said, I have some information as to what is actually broken:

1. Often notification event is not fired at all by the system. E.g. if I create a new event for today, it'll usually fire. But if I create event in two days (with notification at the time of the event), then it will most likely fail to fire.

For this I've implemented a workaround that wakes up every half an hour and scans some time period (e.g. -1 hour to +30 minutes) for CalendarContract.CalendarAlerts.CONTENT_URI_BY_INSTANCE. If any are found and they should've fired already (but didn't), then they are fired 'manually'. Also if there are any alerts upcoming in less than 30 min, then the next rescan is adjusted to coincide with that alert time (so that alerts are fired on time).


2. Alerts are not shown for events that have notifications that are 'long time before the event': I created event 2 weeks + 2 days in the future and set it to notify me 2 weeks before the event -- i.e. it should've fired in 2 days since I've created the event. However I discovered that scanning CalendarContract.CalendarAlerts.CONTENT_URI_BY_INSTANCE completely missed this event (I'm talking about the time when it should've fired, e.g. say it was set March 15, 10:00 in the morning; then it should fire March 1st @ 10:00; scanning March 1st at 10:00 doesn't produce this alert).

This case doesn't seem to even have a 'proper' solution. As a workaround, I scan calendar events 35 days in the future and check all active notifications for them to see if any should be fired manually. This obviously won't work if your notification is more that 35 days before the event, but that the kind of compromise I personally can live with. Since I know nothing about Android programming, I also needed a way to record which such notifications were already fired (so that I avoid firing them again on next rescan or possibly if alert notification fires for them after all -- this case is actually common when creating a new event -- scanning for events + their notifications triggers faster than the same notification becomes available via scanning alerts) -- thus the HashMap stored in file was born.


With these two workaround it seems (so far) that notifications finally work reliably on my phone -- I'm happy :) The battery cost of scanning every ~30 minutes seems to be negligible (it mostly doesn't even register on the list of apps using the battery).


When and if you'll decide to implement some such scanning in your code, I'd like to ask you to produce very detailed logs -- since it is very difficult (time consuming) to reproduce some of these failures, I've made a setup that regularly dumps application's logcat output to file -- that way if something doesn't work as expected it is possible to examine the log to figure out what exactly went wrong -- and this is very valuable in my experience.


Finally the code extract that contains most of my hacks (the rest are trivial additions to other files) -- this is basically at the end of ApplicationController.kt : 
`

    private var rescanInvoked = false;
    /**
     * Rescans calendar for notifications fired since the last one processed.
     * If any are found -- fires those notifications.
     * This method has recursive invocation prevention (does nothing if recursed into).
     */
    fun rescanCalendarAndTriggerNotifications(context: Context) {
        synchronized(this) {
            if (rescanInvoked)
                return;
            try {
                rescanInvoked = true;
                unguardedRescanCalendarAndTriggerNotifications(context)
            } finally {
                rescanInvoked = false;
            }

        }
    }

    /**
     * Rescans calendar for notifications fired since the last one processed.
     * If any are found -- fires those notifications.
     */
    fun unguardedRescanCalendarAndTriggerNotifications(context: Context) {

        logger.debug("SOLF: rescanCalendarAndTriggerNotifications invoked");

        var start = context.globalState.lastTimeNotificationsScanned;
        var alreadyFiredAlerts = context.globalState.alreadyFiredAlerts;
        run {
            val latestLimit = System.currentTimeMillis() - 60 * 60 * 1000; // Scan at least last hour.
            if (latestLimit < start)
                start = latestLimit;

            val earliestLimit = System.currentTimeMillis() - 24 * 60 * 60 * 1000; // Look back max 1 day
            if (earliestLimit > start) {
                start = earliestLimit;
                // It looks like we lost data for the alerts map,
                if (alreadyFiredAlerts.isEmpty()) {
                    logger.debug("SOLF: loading already fired alerts map from file");
                    try {
                        val fis = context.openFileInput("alreadyFiredMap.data")
                        val ois = ObjectInputStream(fis)
                        alreadyFiredAlerts = ois.readObject() as HashMap<String, Long>;
                        context.globalState.alreadyFiredAlerts = alreadyFiredAlerts;
                        ois.close();
                    } catch (e: IOException) {
                        logger.error("SOLF: Failed to load already fired alerts map from file (maybe doesn't exist yet?): ${e}", e)
                    }

                }
            }
        }
        val origAlreadyFiredAlerts = alreadyFiredAlerts.clone();
        logger.debug("SOLF: already fired alerts map at start: ${alreadyFiredAlerts}")

        val end = System.currentTimeMillis() + 30 * 60 * 1000; // Look forward 30 min.
        //val end = System.currentTimeMillis() + 30 * 24 * 60 * 60 * 1000L; // Look forward 30 days.
        if (start >= end) {
            start = end - 1;
            logger.error("SOLF: shouldn't happen -- start is NOT before end, adjusted.");
        }

        logger.info("SOLF: scanning events between ${Date(start)} and ${Date(end)}");
        val cursor: Cursor? =
                context.contentResolver.query(
                        CalendarContract.CalendarAlerts.CONTENT_URI_BY_INSTANCE,
                        CalendarProvider.alertFields,
                        CalendarContract.CalendarAlerts.ALARM_TIME + ">? AND " + CalendarContract.CalendarAlerts.ALARM_TIME + "<=?" ,
                        arrayOf(start.toString(), end.toString()),
                        CalendarContract.CalendarAlerts.ALARM_TIME + " ASC" // Sort Order: CalendarContract.CalendarAlerts.SORT_ORDER_ALARMTIME_ASC
                );

        var nextCheck = end;
        val alertUntil = System.currentTimeMillis() + 10 * 1000; // Stuff that alerts within next 10 seconds gets alerted now.
        if (cursor != null && cursor.moveToFirst()) {
            do {
                val (state, event) = CalendarProvider.cursorToAlertRecord(cursor, null);

                if (state != null && event != null) {
                    logger.debug("SOLF: Scanning event: ${event.title} alert: ${Date(event.alertTime)} ${event.eventId}, st $state, from ${event.startTime} to ${event.endTime}")

                    if (state != CalendarContract.CalendarAlerts.STATE_DISMISSED) {
                        if (event.alertTime <= alertUntil) {
                            if (!alreadyFiredAlerts.containsKey("${event.eventId}_${event.alertTime}")) {
                                logger.info("  -> alerting event: ${event.title} alert: ${Date(event.alertTime)}");
                                onCalendarEventFired(context, event)
                                logger.info("  -> dismissing native event alert");
                                alreadyFiredAlerts.put("${event.eventId}_${event.alertTime}", event.alertTime)
                                logger.info("  -> alerting done");
                            } else {
                                logger.info("  -> NOT alerting event (already fired via calendar scan): ${event.title} alert: ${Date(event.alertTime)}");
                            }
                            CalendarProvider.dismissNativeEventAlert(context, event.eventId);
                        } else {
                            if (event.alertTime < nextCheck) {
                                nextCheck = event.alertTime;
                                logger.debug("  -> this event is in the future, adjusted time for next check");
                            } else {
                                logger.debug("  -> this event is in the future");
                            }
                        }
                    } else {
                        alreadyFiredAlerts.put("${event.eventId}_${event.alertTime}", event.alertTime)
                        logger.debug("  -> this event is dismissed");
                    }
                } else {
                    logger.error("SOLF: Cannot read event details!!")
                }

            } while (cursor.moveToNext())


            cursor.close();
        }

        // Brute-force scan calendar because sometimes notifications don't return in query above.
        run {
            val calEnd = System.currentTimeMillis() + 35/*d*/ * 24/*h*/ * 60/*m*/ * 60/*s*/ * 1000L; // Look forward 35 days.
            logger.info("SOLF: scanning CALENDAR events between ${Date(start)} and ${Date(calEnd)}");

            val eventsUriBuilder = CalendarContract.Instances.CONTENT_URI.buildUpon()
            ContentUris.appendId(eventsUriBuilder, (start - 1)) // Not sure if this is inclusive or not, so extend
            ContentUris.appendId(eventsUriBuilder, (calEnd + 1)) // Not sure if this is inclusive or not, so extend
            val eventsUri = eventsUriBuilder.build()

            val evCursor: Cursor? =
                    context.contentResolver.query(
                            eventsUri,
                            arrayOf(
                                    CalendarContract.Instances.EVENT_ID, // instead of CalendarContract.CalendarAlerts.EVENT_ID,
                                    CalendarContract.Events.ALL_DAY, // ignored really, instead of CalendarContract.CalendarAlerts.STATE,
                                    CalendarContract.Events.CALENDAR_ID,
                                    CalendarContract.Events.TITLE,
                                    CalendarContract.Events.DTSTART,
                                    CalendarContract.Events.DTEND,
                                    CalendarContract.Events.EVENT_LOCATION,
                                    CalendarContract.Events.DISPLAY_COLOR,
                                    CalendarContract.Instances.BEGIN, // replaced later, instead of CalendarContract.CalendarAlerts.ALARM_TIME,
                                    CalendarContract.Instances.BEGIN, // instead of CalendarContract.CalendarAlerts.BEGIN,
                                    CalendarContract.Instances.END, // instead of CalendarContract.CalendarAlerts.END,
                                    CalendarContract.Events.ALL_DAY
                            ),
                            null,
                            null,
                            CalendarContract.Instances.BEGIN + " ASC"
                    );

            if (evCursor != null && evCursor.moveToFirst()) {
                do {
                    val (state, event) = CalendarProvider.cursorToAlertRecord(evCursor, null);

                    if (state != null && event != null) {

                        logger.debug("SOLF: CALENDAR event: ${event.title} @ ${Date(event.instanceStartTime)}");

                        run {
                            val reminderCursor: Cursor? =
                                    context.contentResolver.query(
                                            CalendarContract.Reminders.CONTENT_URI,
                                            arrayOf(CalendarContract.Reminders.METHOD,
                                                    CalendarContract.Reminders.MINUTES
                                            ),
                                            "${CalendarContract.Reminders.EVENT_ID}=?", // WHERE_EVENT_ID
                                            arrayOf(event.eventId.toString()),
                                            null
                                    );

                            if (reminderCursor != null && reminderCursor.moveToFirst()) {
                                do {
                                    val reminderType = reminderCursor.getInt(0);
                                    val reminderBeforeMinutes = reminderCursor.getInt(1);

                                    if ((reminderType == CalendarContract.Reminders.METHOD_ALERT) or ((reminderType == CalendarContract.Reminders.METHOD_DEFAULT))) {
                                        val alertTime = event.instanceStartTime - 60/*s*/ * 1000L * reminderBeforeMinutes;
                                        if (alertTime >= start) {

                                            if (alertTime <= alertUntil) {

                                                if (!alreadyFiredAlerts.containsKey("${event.eventId}_${alertTime}")) {
                                                    event.alertTime = alertTime;
                                                    logger.info("  -> ALERTING: type: ${reminderType}, @ -${reminderBeforeMinutes}min => ${Date(alertTime)}");
                                                    onCalendarEventFired(context, event)
                                                    alreadyFiredAlerts.put("${event.eventId}_${event.alertTime}", event.alertTime)
                                                    logger.info("  -> alerting done");
                                                } else {
                                                    logger.debug("  -> already fired, type: ${reminderType}, @ -${reminderBeforeMinutes}min => ${Date(alertTime)}");
                                                }
                                            } else {
                                                if (alertTime < nextCheck) {
                                                    nextCheck = alertTime;
                                                    logger.debug("  -> this R is in the future, adjusted time for next check, type: ${reminderType}, @ -${reminderBeforeMinutes}min => ${Date(alertTime)}");
                                                } else {
                                                    logger.debug("  -> this R is in the future, type: ${reminderType}, @ -${reminderBeforeMinutes}min => ${Date(alertTime)}");
                                                }
                                            }

                                        } else {
                                            logger.debug("  -> too old R, type: ${reminderType}, @ -${reminderBeforeMinutes}min => ${Date(alertTime)}");
                                        }
                                    } else {
                                        logger.debug("  -> ignored R, type: ${reminderType}, @ -${reminderBeforeMinutes}min");
                                    }
                                } while (reminderCursor.moveToNext())


                                reminderCursor.close();
                            }
                        }

                    }
                } while (evCursor.moveToNext())

                logger.debug("SOLF: done scanning Calendar events");


                evCursor.close();
            }

        }

        context.globalState.lastTimeNotificationsScanned = alertUntil;

        // Need to expire old records in already fired map
        run {
            val oldestToKeep = System.currentTimeMillis() - 24 * 60 * 60 * 1000L; // discard those older than yesterday
            val iter = alreadyFiredAlerts.entries.iterator();
            while (iter.hasNext()) {
                val entry = iter.next();
                if (entry.value < oldestToKeep) {
                    iter.remove();
                    logger.debug("SOLF: expired fired event entry: ${entry}");
                }
            }
        }

        // Save already fired map unless it hasn't changed.
        if (!origAlreadyFiredAlerts.equals(alreadyFiredAlerts)) {
            logger.debug("SOLF: saving already fired alerts map: ${alreadyFiredAlerts}")
            try {
                val fos = context.openFileOutput("alreadyFiredMap.data", Context.MODE_PRIVATE);
                val oos = ObjectOutputStream(fos);
                oos.writeObject(alreadyFiredAlerts);
                oos.flush();
                oos.close();
            } catch (e: IOException) {
                logger.error("SOLF: Failed to write already fired alerts map: ${e}", e)
            }
        } else {
            logger.debug("SOLF: NOT saving already fired alerts map (not changed): ${alreadyFiredAlerts}")
        }

        run {
            val minValue = System.currentTimeMillis() + 7;
            if (nextCheck < minValue) {
                logger.error("Next rescan target is too early, changed ${Date(nextCheck)} to ${Date(minValue)}");
                nextCheck = minValue;
            }
        }

        run {
            // Calendar change event doesn't seem to show up immediately (in terms of notification times)
            // and we can't depend on EventReminderBroadcastReceiver working correctly, so rescan several times with some delay
            val timeSinceLastCalendarEvent = System.currentTimeMillis() - context.globalState.lastCalendarChangeEvent;
            var limit = nextCheck;
            if (timeSinceLastCalendarEvent >= 0) { // Sanity check
                if (timeSinceLastCalendarEvent < 10 * 1000) {
                    limit = System.currentTimeMillis() + 11 * 1000; // First rescan is quick
                } else if (timeSinceLastCalendarEvent < 120 * 1000) {
                    limit = System.currentTimeMillis() + 60 * 1000; // Subsequent rescans not so quick
                }
            }

            if (limit < nextCheck) {
                logger.info("Calendar changed recently, next rescan at ${Date(limit)} instead of ${Date(nextCheck)}")
                nextCheck = limit;
            }
        }

        logger.info("Scheduling next rescan at: ${Date(nextCheck)}");
        context.alarmManager.setExactAndAlarm(
                context,
                getSettings(context),
                nextCheck,
                RescanAlarmBroadcastReceiver::class.java, // ignored on KitKat and below
                RescanExactAlarmBroadcastReceiver::class.java,
                MainActivity::class.java,
                logger)


        logger.debug("SOLF: rescanCalendarAndTriggerNotifications done");
    }
`


Yes, the above code sucks, sorry about that ;) Feel free to use any of it if you find something useful in there.

P.S. Is there a sane way to dump application's logcat information to some file? I currently run a script that every 5 minutes runs (as root) something like:
`logcat -t <last time logcat was run> | fgrep CalNotif >> somefile`

**Comment by quarck** [comment]
Hi, 

Very much appreciate your effort. 

As you might have seen in the "NOTE" to the project, I'm currently very very short on free time. This would last until end of April. 

As soon as I can - I'd take a closer look at your changes and integrate them into the project. 

P.S. regarding logcat -- you can change buffer size in android developer settings, setting it to something like 4M should be sufficient to keep at least half day of logs. 

Thanks, 
Sergey

**Comment by solf** [comment]
Trying to be a bit more helpful for when you have time to get back to this :)

Here's the patch I've generated for all the changes I've made: https://yadi.sk/d/-oCCdcb93GkHYz

This has been done on Windows with GNU diff so I don't know if it might have some underlying problems (not the stuff I usually do :)). I was able to successfully use it to patch with: patch -p1 < patch.data

This is against the code I apparently downloaded (as zip) from master on 17 March (sorry I can't be more precise).

In addition to hooking the method I've listed before in various places (particularly alert notification event now simply calls my scan method -- this e.g. avoids double-firing of events in some situations) the patch also contains my attempt at adding TTS.

I saw your code trying to do the same, but as far as I was able to tell -- TTS doesn't seem to work unless application is in foreground. It probably should be possible to do TTS if you post notification in some special way (e.g. various navigation programs and youtube can play sounds even if they are not in foreground) -- however this is far above what I realistically do with my near-0 knowledge of Android programming.

So my hack is two-fold:
1. If snooze action is displayed within some 3 seconds after an alert -- it plays TTS (TTS code I googled up works in this case -- it didn't work in other places I tried -- I assume it works because app is now in foreground).
2. I use external app (Automate) to immediately click snooze notifications when screen is off -- this causes TTS to play -- and I prefer snooze activity to be open when I turn the phone on anyway.

In the future it would be nice to add an option to auto-open Snooze activity, e.g.: Never/Screen Off/Always

**Comment by solf** [comment]
I've updated patch (modified link in previous post to point to the new patch):

- Fixes bug with repeating calendar events behaving very strangely on subsequent events (caused by event reloading failing to find event by alert -- as mentioned previously search by alert is not reliable on my phone -- a fix/workaround is to brute force search calendar again). With old code this can be reproduced on any (?) phone by creating event in the past (say 2 weeks with weekly repeat) -- calendar is updated (and reacted to) before alerts actually are available from the query service.

- Fixed bug where TTS would reference first event start time rather than current instance's (again bug with repeating events).

- Modified TTS format to a simple X days, Y hours, Z minutes (with unnecessary parts omitted and minutes not reported if there are days).

**Comment by quarck** [comment]
Finally implemented. See git label 'fix_for_bug_208'. Perhaps needs more testing, so no new releases for a while.
