### ISSUE TITLE
Missing event notifications for overlapping events.

### ISSUE THREAD

**Issue by solf** [quarck/CalendarNotification#219]
On my OnePlus 3T (Marshmallow) the following happens:

- 'setAlarmClock' is checked
- 'Enable reminders' is checked
- Remind interval is set to 10 minutes
- Create event Test1, set it to notify at 9:00
- Create event Test2, set it to notify at 9:30
- Test1 triggers -- ignore it -- it will keep reminding every 10 minutes, keep ignoring it.
- At 9:35 (basically after 9:30) observe that Test2 notification never showed up; you can, for example, dismiss Test1 notification and Test2 will not be alerted -- nor would it appear in 'recently dismissed' -- basically it's lost.

Some background info -- on my system it looks like standard calendar notifications are broken for whatever reason -- they often (always?) don't trigger at all unless event was created less than 1-2 days before. It is broken that way both in Google Calendar and Calendar Snooze (which I always used on my previous phones).

This is the reason I came to this application and tried using setAlarmClock option. This seems to work so far -- EXCEPT for the case with overlapping notifications outlined above.

**Comment by quarck** [comment]
Hi,

Thanks for reporting this bug.

My app relies on the Android system (calendar provider service) to fire
events on time. Stock calendar and Calendar Snooze are doing the same.
For this reason all these apps would not work if calendar provider is
somehow broken.

I have some changes planned to implement 'direct scheduling' bypassing
calendar provider, but due to personal circumstances I would only start
working on it in May. After this change, bugs like this one should go away.

Thanks,
Sergey

**Comment by solf** [comment]
In all probability these are derivatives of general problem of notification events failing to fire on certain systems: https://github.com/quarck/CalendarNotification/issues/208

With workarounds I've posted in that issue this problem is gone.
