### ISSUE TITLE
Stopped Receiving Notifications

### ISSUE THREAD

**Issue by neilschelly** [quarck/CalendarNotification#239]
I stopped receiving the notifications yesterday sometime. I'm currently running 1.4.1, but this started on the release before that. I upgraded hoping it would fix the problem.

What does happen: 
The screen turns on when a notification _should_ happen. I don't get the notification sound. If I open up the app directly, it will have the active notifications listed that I can interact with normally. Opening the app will also cause the notifications to show up in the notification bar, but this appears to only happen sometimes.

I don't know any particular updates that might have corresponded with this change. I saw your reply to another person's review on Google Play reporting what appears to be a similar problem. The app is not blocked from notifications and the app still has Calendar access.

**Comment by quarck** [comment]
Hi,

It would help if you could send me app logs immediately after seeing this
issue.
To do that click on "help and feedback", tick "attach app logs" checkbook
and click on "email developer" and send the email. It would not contain any
private event details.

Meanwhile, your could install version 1.3.23 from f-droid.org to get it
working for you (you would need to uninstall it first as f-droid is using
their own keys for signing builds).

Thanks,
Sergey

**Comment by neilschelly** [comment]
I sent you the logs and downgraded. Notifications are working as expected now. Let me know how else I can help. My employer probably prohibits easily contributing code. :-(

**Comment by quarck** [comment]
Hi Neil, 

I did a look at the log file, apparently android often truncates these logs to just recent few minutes (it is a ring buffer in memory), so not really very useful. 

I just published a new version to play store - 1.4.2, it fixes some other bugs and potentially should improve situation with your device as well. What it also has is ability to keep its own logs in the local storage. 

I would appreciate if you could try this build once again, and enable that setting to keep all the logs (Under settings -> misc), and use it for a while to see if you would be able to reproduce this issue. 
Even if you could not reproduce this issue - please submit me the updated log file after a couple of days - it might still log some exception details that might have suggest cause of original problem. After submitting me the new log - please don't forget to disable that setting, by disabling you would clear all the collected logs. If not disabled - it would keep constantly logs indefinitely. 

To install 1.4.2 from play store you would need to un-install F-Droid version completely once again since signing keys are different. 

Thanks, 
Sergey

**Comment by neilschelly** [comment]
Sorry for the delay getting back to you. I have upgraded to the latest release (1.4.6 now) and turned on the logs. So far, things seem to be working.

Also, I think it's possible I forgot to turn off the Battery Optimization for that app before when I was missing notifications. I know the description includes a reminder to do that, but I missed it apparently. I'd never had a problem before, but if this potentially weighs in, I wanted to make it known. The battery optimization is off now.

**Comment by neilschelly** [comment]
I've been running the latest version from the store for a few days now. Things have been working well again with no hiccups. I think it's safe to call this bug fixed.

**Comment by quarck** [comment]
Thanks for confirming!
