### ISSUE TITLE
Reminder Notifications

### ISSUE THREAD

**Issue by KeyopK** [quarck/CalendarNotification#240]
Hi Sergey,

Firstly, thanks for this app, it is very useful.

Since yesterday I am receiving an additional heads-up notification at each reminder interval (every minute in my settings).

This heads-up notifcation says: 

"Reminder: You have missed event"
"Last notification: 1 minute ago, reminder 1 of 0"

Can you tell me how I turn off these heads-up reminder notifcations without turning off the original event heads-up notification?

I hope this makes sense. If you could point me in the right direction, that would be great.

Thanks and regards,

Ed

**Comment by quarck** [comment]
Hi Ed,

Thank you for your report. Making this reminder notifications as a heads-up
was completely accidental - will be fixed in the next build (expected today
/ tomorrow).
It would be still a separate notification for reminders, but would not show
heads-up. (Separate notification is more reliable and eliminates problems
that happen on some devices)

Thanks,
Sergey

**Comment by quarck** [comment]
Fixed in d9241e34a0c6d8f4e6e0119f0aa02bc4f82b3339, included in the build 1.4.2 - it is on the way to play store
