### ISSUE TITLE
After snoozing notification Calendar Notification stays open in task switcher

### ISSUE THREAD

**Issue by aibaraiduas** [quarck/CalendarNotification#3]
When a event notification is snoozed, Calendar Notification keeps an open window in the task switcher. Since the point of snoozing the event is to put it out of sight and mind for a certain amount of time, CN should not be visible. Tested on a Nexus 5 running Android 6.0.1.

Thanks.

**Comment by quarck** [comment]
Thanks for reporting. I'd try to take a look at this bug and #4 over the weekend.

**Comment by quarck** [comment]
This should be fixed now in the version 1.0.6. This version is currently going through publishing process on Google Play (it takes a few hours at least for Google to approve the app). 

I'm holing of with publishing it to F-Droid until I'm certain that several other bugs are fixed - it is manual process for F-Droid moderators to build the app and publish - just want to save them some work. 

Right now you can get new version from my Dropbox: https://dl.dropboxusercontent.com/u/25074445/cnotify/CalendarNotificationPlus_1.0.6.apk
It is signed with the same key as the version on Google Play Store. If you have installed it from F-Droid  previously - please uninstall it first. (F-Droid guys building apps themselves and signing with their own keys, so I can't sign with the same key). 

Closing now since my testing confirms it is fixed. Please reopen if necessary.
