### ISSUE TITLE
Icons are too light & low res

### ISSUE THREAD

**Issue by aibaraiduas** [quarck/CalendarNotification#5]
This is a pretty minor issue, but the snooze and dismiss icons' gray color are too light; they should be the same darkness as the text next to them. They also seem slightly low res and blurry on my device (a Nexus 5, which has an XXHDPI screen I think). For comparison, other apps (FastMail and Signal in this case) have crisper and darker icons.

Thanks for the useful app!

![screenshot_20160307-140546](https://cloud.githubusercontent.com/assets/5825551/13594313/5cdfcca4-e4d1-11e5-82b2-2dd7583a19de.png)
![screenshot_20160307-140601](https://cloud.githubusercontent.com/assets/5825551/13594315/5ce0f228-e4d1-11e5-9cd6-840c1a67122c.png)
![screenshot_20160307-205623](https://cloud.githubusercontent.com/assets/5825551/13594314/5ce0f0ca-e4d1-11e5-817f-31b71f3454da.png)

**Comment by quarck** [comment]
Hi, 

Thanks for detailed report. I'd take a look, but this time it might take a bit longer until I'd have a time for that - some other deadlines approaching on the end of March. 

P.S. For these two icons I'm using built-in android icons and I was hoping them to look properly on each device (simply because each device has it's own version of these icons that is adopted for device UI theme). But it looks like I need to put custom icons into the app for that. 

Thanks, 
Sergey

**Comment by quarck** [comment]
Icons updated in 9d2b1a449cfd9d10af3cda99ea5ed20e1d2d3d7f
